Style/Documentation:
  Enabled: false
Naming/MethodParameterName:
  Enabled: false
Metrics/MethodLength:
  Max: 10000
Style/FrozenStringLiteralComment:
  Enabled: false
Style/EndOfLine:
  EnforcedStyle: lf
ClassAndModuleChildren:
  Enabled: false
GuardClause:
  Enabled: false
IfUnlessModifier:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Layout/IndentationWidth:
  Enabled: false
Layout/LineLength:
  Enabled: false
Layout/AccessModifierIndentation:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false